// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonGEH_WebAPI_Unit_Testing.Data;

#nullable disable

namespace PersonGEH_WebAPI_Unit_Testing.Migrations
{
    [DbContext(typeof(DbContextClass))]
    partial class DbContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonGEH_WebAPI_Unit_Testing.Model.PersonDetails", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailId");

                    b.ToTable("PersonDetalisTest");
                });

            modelBuilder.Entity("PersonGEH_WebAPI_Unit_Testing.Model.TechnicalExperience", b =>
                {
                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonDetailsEmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TechnologyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkedTo")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyName");

                    b.HasIndex("PersonDetailsEmailId");

                    b.ToTable("TechnicalExperiencesTest");
                });

            modelBuilder.Entity("PersonGEH_WebAPI_Unit_Testing.Model.TechnicalExperience", b =>
                {
                    b.HasOne("PersonGEH_WebAPI_Unit_Testing.Model.PersonDetails", null)
                        .WithMany("TechnicalExperiences")
                        .HasForeignKey("PersonDetailsEmailId");
                });

            modelBuilder.Entity("PersonGEH_WebAPI_Unit_Testing.Model.PersonDetails", b =>
                {
                    b.Navigation("TechnicalExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
